
import unittest
from . import main


class TestLongestCommonSubstring(unittest.TestCase):

    def test_sample1(self):
        seqs = ["GATTACA", "TAGACCA", "ATACA"]
        lcs = main.longest_common_substring(seqs)
        self.assertTrue(lcs == "AC" or lcs == "TA", "lcs should be AC or TA")

    def test_example(self):
        seqs = ["ACGTACGT", "AACCGTATA"]
        lcs = main.longest_common_substring(seqs)
        self.assertEqual(lcs, "CGTA")

    def test_sample2(self):
        seqs = ["ABHMZNBTHSOMZBZPUCNDAESLLGBIDACZRULGJEQCAMYDOGHASFLEASLSYBKGIQBLVVIFZXZURSLQNARHUIXCEMWMZT",   # noqa
                "CLBKIIMAFEYIBCYHLRGXWIEJMYDOGHASFLEASWYQEVJBRKPZJXPNFJCVJKJLEZWAVLQYPTKTBBXZDKHIOFRRQXMHRE",   # noqa
                "NSKCDOZPLCXSTINBXJEPDEOIBRTJTZALMFCPCTTHEIBYYAOMLANSEGUTPYRKQTZMYDOGHASFLEASUNIIPXKILSTKZT",   # noqa
                "BXHLFCJOTNPGHRFMYDOGHASFLEASHJQAOJBQPWJPJAOSAHSGBPMQHFUHNGIHZRGLSNVNSUUOFGSIMYWHNOLCKGNTMN",   # noqa
                "XYCALILLEWGEHIMYDOGHASFLEASIILJQNASXHMAMFGXQHZMCPRRYRMQKSSAXALDAKKJKLESNARKTUUYHDXJTKBFELL",   # noqa
                "KIIEQSTSTNZGBSRMZDVHPBTWJKIVYOMYDOGHASFLEASYZBBLZBFNHEVJWTLSNKUDPDKLBMXKRVLUFGVUNVBHVBCLZZ",   # noqa
                "PDZAGGUZMLVEJGFMUVTDZBXXUBPCQHCBMYDOGHASFLEASELDHQOHIDWFXIAPULQXIDOQEACOFPPZVHDKZAEVOHNDAV",   # noqa
                "XLWYWXINXTKIMBCDCVSNDZCEPQZAJLWSTKTMVJWFVRXDWZVRTFJVIHCMDTYGRUFVSMYDOGHASFLEASPGRMNIJVWFUQ",   # noqa
                "UDLRQHDIHMFBYXRZXOSLVIPTUCWQHSEEDIRMYUWIXFAOMPRSFZMYDOGHASFLEASHSDOZHTXTFGGDLYYKGZMWDOHDPP",   # noqa
                "YVMTCPNQIKYDVTEAGAHTQTTBAZQNEWETFBBHZRPUYCMCHNOMYDOGHASFLEASZFLPAMCVXFSTRWJHXGHRTCYWYIMXTD",   # noqa
                "WQEWNBNCMPAXRDCSUGGGXIWUCXIAVBLKBMPUABYEBTTAMYDOGHASFLEASPBBNSRLVYAKEKLCNUUKINKMRCCBSTZKSF",   # noqa
                "KAHSXDDYHJOPTARBGZGTXGXZZSQRXXBFUXSZBGTSWIZPKZNKLJBYJXOERERNDTBTJUYFWMYDOGHASFLEASLRTEHILP",   # noqa
                "ZMYDOGHASFLEASIZSQHLLMWPTQASLBQEIFNJGXUALETFKXBUOITEXRTCILKVHHCEPLPXFLMWVEADXXVNMTXACIRXGT",   # noqa
                "AFIJZMQPLMXBEHXGHHQECYNLSZZXXYDBVOMYDOGHASFLEASQFKWNEBOSRYSCAUXXLWUOOMBLAASYPZFVUQNILHQJMT",   # noqa
                "URCMTRURJNMWEOFVGCEAHBLXBUCFRBPFIULXWXVGDWOQXHMYDOGHASFLEASEUIRPCUHBWYJRRUZDJFWVYFZVTULHOG",   # noqa
                "JBXLDORUHNHUKMOACGMYDOGHASFLEASIVLEZWYLJJTERLRMOJGAVDSLDPFKWBECCSQCCTPJTYFERYGJNRTMOPIMNKI",   # noqa
                "JKLCQNTJHBFSJFHUHSIWYLVWNVIWQISBPDSBJOPFDNYSTAHWGOCZGBPPVAGZBJCJUIENMYDOGHASFLEASYLEVAHLLQ",   # noqa
                "NHUBXCIYCIUIRRDPSOUUBMAHAVELFPEBQLSMAMMDOMYDOGHASFLEASBPHNRZVHAGXIJQZDCXFQSNLANGGSDESJNFIA",   # noqa
                "WJZGLIYHWJNDMYDOGHASFLEASTZAOKYTWHHIXLSUHACQDWTUCKXAXBXKAFYGJGMTYITMKCJZJYFXDOZBRJZKQTNPBF",   # noqa
                "FGAMAFYEYQLHUSMSSKPTWZDGUUPZQMXLXVIGZFIRCDKBMZXORWJUHNGQKQEPTNSIMYDOGHASFLEASJPTSRJRUFLUNB"]   # noqa
        lcs = main.longest_common_substring(seqs)
        self.assertEqual(lcs, "MYDOGHASFLEAS")


if __name__ == '__main__':
    unittest.main()
